name: "✨ Feature Request"
description: "새로운 기능 개발이 필요한 경우 작성합니다."
title: "[Feat] "
labels: ["feat"]
body:
  - type: textarea
    id: feature-summary
    attributes:
      label: "📌 기능 설명"
      description: "어떤 기능을 개발해야 하는지 구체적으로 적어주세요."
      placeholder: "예: 회의 중 실시간 음성 텍스트 변환 기능"
    validations:
      required: true

  - type: textarea
    id: feature-details
    attributes:
      label: "⚙️ 구현 내용"
      description: "개발 시 참고할 만한 아이디어, 로직, 화면 흐름 등을 자유롭게 작성해주세요."
      placeholder: "예: 음성 → 텍스트는 Whisper API 사용, 출력은 오른쪽 패널에 표시"
    validations:
      required: false

  - type: input
    id: feature-deadline
    attributes:
      label: "📆 목표 완료일 (선택)"
      description: "해당 기능이 완료되어야 하는 목표 날짜가 있다면 적어주세요."
      placeholder: "예: 2024-07-15"
    validations:
      required: false

  - type: checkboxes
    id: feature-scope
    attributes:
      label: "🔍 예상 작업 범위"
      description: "이 기능에 포함될 작업 범위를 체크해주세요."
      options:
        - label: "프론트엔드 UI 개발"
        - label: "백엔드 API 연동"
        - label: "상태 관리 / 데이터 흐름"
        - label: "테스트 코드 작성"
